# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.11.3

pipelines:
  branches:
    bishkekfire-ru:
      - step:
          caches:
            - node
          name: Deploy to Heroku  
          deployment: test   # set to test, staging or production
          script: # Modify the commands below to build your repository.
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/businessbishkek.git HEAD:master
                

